import {
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowDown,
  ArrowLeftCircle,
  ArrowLeft,
  ArrowRightCircle,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart2,
  BarChart,
  BatteryCharging,
  Battery,
  BellOff,
  Bell,
  Bluetooth,
  Bold,
  BookOpen,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  CameraOff,
  Camera,
  Cast,
  CheckCircle,
  CheckSquare,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Chrome,
  Circle,
  Clipboard,
  Clock,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Cloud,
  Code,
  Codepen,
  Codesandbox,
  Coffee,
  Columns,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  DivideCircle,
  DivideSquare,
  Divide,
  DollarSign,
  DownloadCloud,
  Download,
  Dribbble,
  Droplet,
  Edit2,
  Edit3,
  Edit,
  ExternalLink,
  EyeOff,
  Eye,
  Facebook,
  FastForward,
  Feather,
  Figma,
  FileMinus,
  FilePlus,
  FileText,
  File,
  Film,
  Filter,
  Flag,
  FolderMinus,
  FolderPlus,
  Folder,
  Framer,
  Frown,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitHub,
  Gitlab,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link2,
  Link,
  Linkedin,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Map,
  Maximize2,
  Maximize,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  MicOff,
  Mic,
  Minimize2,
  Minimize,
  MinusCircle,
  MinusSquare,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Navigation2,
  Navigation,
  Octagon,
  Package,
  Paperclip,
  PauseCircle,
  Pause,
  PenTool,
  Percent,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Phone,
  PieChart,
  PlayCircle,
  Play,
  PlusCircle,
  PlusSquare,
  Plus,
  Pocket,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Share,
  ShieldOff,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Tool,
  Trash2,
  Trash,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitch,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  UploadCloud,
  Upload,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  User,
  Users,
  VideoOff,
  Video,
  Voicemail,
  Volume1,
  Volume2,
  VolumeX,
  Volume,
  Watch,
  WifiOff,
  Wifi,
  Wind,
  XCircle,
  XOctagon,
  XSquare,
  X,
  Youtube,
  ZapOff,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'react-feather';

let components = {
  activity: Activity,
  airplay: Airplay,
  alertcircle: AlertCircle,
  alertoctagon: AlertOctagon,
  alerttriangle: AlertTriangle,
  aligncenter: AlignCenter,
  alignjustify: AlignJustify,
  alignleft: AlignLeft,
  alignright: AlignRight,
  anchor: Anchor,
  aperture: Aperture,
  archive: Archive,
  arrowdowncircle: ArrowDownCircle,
  arrowdownleft: ArrowDownLeft,
  arrowdownright: ArrowDownRight,
  arrowdown: ArrowDown,
  arrowleftcircle: ArrowLeftCircle,
  arrowleft: ArrowLeft,
  arrowrightcircle: ArrowRightCircle,
  arrowright: ArrowRight,
  arrowupcircle: ArrowUpCircle,
  arrowupleft: ArrowUpLeft,
  arrowupright: ArrowUpRight,
  arrowup: ArrowUp,
  atsign: AtSign,
  award: Award,
  barcharttwo: BarChart2,
  barchart: BarChart,
  batterycharging: BatteryCharging,
  battery: Battery,
  belloff: BellOff,
  bell: Bell,
  bluetooth: Bluetooth,
  bold: Bold,
  bookopen: BookOpen,
  book: Book,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  calendar: Calendar,
  cameraoff: CameraOff,
  camera: Camera,
  cast: Cast,
  checkcircle: CheckCircle,
  checksquare: CheckSquare,
  check: Check,
  chevrondown: ChevronDown,
  chevronleft: ChevronLeft,
  chevronright: ChevronRight,
  chevronup: ChevronUp,
  chevronsdown: ChevronsDown,
  chevronsleft: ChevronsLeft,
  chevronsright: ChevronsRight,
  chevronsup: ChevronsUp,
  chrome: Chrome,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  clouddrizzle: CloudDrizzle,
  cloudlightning: CloudLightning,
  cloudoff: CloudOff,
  cloudrain: CloudRain,
  cloudsnow: CloudSnow,
  cloud: Cloud,
  code: Code,
  codepen: Codepen,
  codesandbox: Codesandbox,
  coffee: Coffee,
  columns: Columns,
  command: Command,
  compass: Compass,
  copy: Copy,
  cornerdownleft: CornerDownLeft,
  cornerdownright: CornerDownRight,
  cornerleftdown: CornerLeftDown,
  cornerleftup: CornerLeftUp,
  cornerrightdown: CornerRightDown,
  cornerrightup: CornerRightUp,
  cornerupleft: CornerUpLeft,
  cornerupright: CornerUpRight,
  cpu: Cpu,
  creditcard: CreditCard,
  crop: Crop,
  crosshair: Crosshair,
  database: Database,
  delete: Delete,
  disc: Disc,
  dividecircle: DivideCircle,
  dividesquare: DivideSquare,
  divide: Divide,
  dollarsign: DollarSign,
  downloadcloud: DownloadCloud,
  download: Download,
  dribbble: Dribbble,
  droplet: Droplet,
  edittwo: Edit2,
  editthree: Edit3,
  edit: Edit,
  externallink: ExternalLink,
  eyeoff: EyeOff,
  eye: Eye,
  facebook: Facebook,
  fastforward: FastForward,
  feather: Feather,
  figma: Figma,
  fileminus: FileMinus,
  fileplus: FilePlus,
  filetext: FileText,
  file: File,
  film: Film,
  filter: Filter,
  flag: Flag,
  folderminus: FolderMinus,
  folderplus: FolderPlus,
  folder: Folder,
  framer: Framer,
  frown: Frown,
  gift: Gift,
  gitbranch: GitBranch,
  gitcommit: GitCommit,
  gitmerge: GitMerge,
  gitpullrequest: GitPullRequest,
  github: GitHub,
  gitlab: Gitlab,
  globe: Globe,
  grid: Grid,
  harddrive: HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  helpcircle: HelpCircle,
  hexagon: Hexagon,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  instagram: Instagram,
  italic: Italic,
  key: Key,
  layers: Layers,
  layout: Layout,
  lifebuoy: LifeBuoy,
  linktwo: Link2,
  link: Link,
  linkedin: Linkedin,
  list: List,
  loader: Loader,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  mappin: MapPin,
  map: Map,
  maximizetwo: Maximize2,
  maximize: Maximize,
  meh: Meh,
  menu: Menu,
  messagecircle: MessageCircle,
  messagesquare: MessageSquare,
  micoff: MicOff,
  mic: Mic,
  minimizetwo: Minimize2,
  minimize: Minimize,
  minuscircle: MinusCircle,
  minussquare: MinusSquare,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  morehorizontal: MoreHorizontal,
  morevertical: MoreVertical,
  mousepointer: MousePointer,
  move: Move,
  music: Music,
  navigationtwo: Navigation2,
  navigation: Navigation,
  octagon: Octagon,
  package: Package,
  paperclip: Paperclip,
  pausecircle: PauseCircle,
  pause: Pause,
  pentool: PenTool,
  percent: Percent,
  phonecall: PhoneCall,
  phoneforwarded: PhoneForwarded,
  phoneincoming: PhoneIncoming,
  phonemissed: PhoneMissed,
  phoneoff: PhoneOff,
  phoneoutgoing: PhoneOutgoing,
  phone: Phone,
  piechart: PieChart,
  playcircle: PlayCircle,
  play: Play,
  pluscircle: PlusCircle,
  plussquare: PlusSquare,
  plus: Plus,
  pocket: Pocket,
  power: Power,
  printer: Printer,
  radio: Radio,
  refreshccw: RefreshCcw,
  refreshcw: RefreshCw,
  repeat: Repeat,
  rewind: Rewind,
  rotateccw: RotateCcw,
  rotatecw: RotateCw,
  rss: Rss,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  sharetwo: Share2,
  share: Share,
  shieldoff: ShieldOff,
  shield: Shield,
  shoppingbag: ShoppingBag,
  shoppingcart: ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  skipback: SkipBack,
  skipforward: SkipForward,
  slack: Slack,
  slash: Slash,
  sliders: Sliders,
  smartphone: Smartphone,
  smile: Smile,
  speaker: Speaker,
  square: Square,
  star: Star,
  stopcircle: StopCircle,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  thumbsdown: ThumbsDown,
  thumbsup: ThumbsUp,
  toggleleft: ToggleLeft,
  toggleright: ToggleRight,
  tool: Tool,
  trashtwo: Trash2,
  trash: Trash,
  trello: Trello,
  trendingdown: TrendingDown,
  trendingup: TrendingUp,
  triangle: Triangle,
  truck: Truck,
  tv: Tv,
  twitch: Twitch,
  twitter: Twitter,
  type: Type,
  umbrella: Umbrella,
  underline: Underline,
  unlock: Unlock,
  uploadcloud: UploadCloud,
  upload: Upload,
  usercheck: UserCheck,
  userminus: UserMinus,
  userplus: UserPlus,
  userx: UserX,
  user: User,
  users: Users,
  videooff: VideoOff,
  video: Video,
  voicemail: Voicemail,
  volumeone: Volume1,
  volumetwo: Volume2,
  volumex: VolumeX,
  volume: Volume,
  watch: Watch,
  wifioff: WifiOff,
  wifi: Wifi,
  wind: Wind,
  xcircle: XCircle,
  xoctagon: XOctagon,
  xsquare: XSquare,
  x: X,
  youtube: Youtube,
  zapoff: ZapOff,
  zap: Zap,
  zoomin: ZoomIn,
  zoomout: ZoomOut,
};

let IconSelector = ({ icon, stroke, fill, size }) => {
  let Icon = components[icon];
  if (Icon) {
    return <Icon stroke={stroke} fill={fill} size={size} />;
  }
  return null;
};

export default IconSelector;
