import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Page from './page';
import { generateImage } from '../utils/utils';
import IconSelector from '../utils/IconSelector';
import { Camera, Download } from 'react-feather';
import { useRef, useState, useEffect } from 'react';
import StrokeSelector from '../utils/StrokeSelector';

let Home = () => {
  const IconRef = useRef(null);

  const [activeIcon, updateActiveIcon] = useState({
    icon: 'camera',
    stroke: 'white',
    backgroundColor: 'black',
    fill: 'black',
  });

  let [downloading, updateDownloading] = useState(false);
  let downloadIcon = (thisicon) => {
    updateActiveIcon(thisicon);
    updateDownloading(true);
  };

  let [stroke, updateStroke] = useState('#ffffff');
  let [fill, updateFill] = useState('#000000');
  let [backgroundColor, updateBackgroundColor] = useState('black');

  useEffect(() => {
    if (downloading) {
      generateImage(IconRef.current);
      updateDownloading(false);
    }
  }, [downloading, activeIcon]);

  return (
    <div className="relative">
      <div className="fixed top-0 left-0 z-0">
        {activeIcon && (
          <RenderBigIcon
            ref={IconRef}
            activeIcon={activeIcon}
            stroke={stroke}
            fill={fill}
            backgroundColor={backgroundColor}
          />
        )}
      </div>
      <div className="relative z-10 w-full h-full bg-gray-100 ">
        <Page>
          <div className="ml-4 mr-11 md:mr-9 lg:mr-16">
            <div
              style={{ background: backgroundColor, color: stroke }}
              className="flex items-center justify-center inline-block w-10 h-10 font-bold text-white bg-black rounded-apple"
            >
              i
            </div>
            <p className="mt-4 text-gray-600">
              Twitter is going insane over custom iOS14 icons. Here are{' '}
              <a
                className="font-bold"
                href="https://github.com/feathericons/feather"
              >
                Feather Icons
              </a>
              , sized for use on your phone. Click on an icon to download it.{' '}
            </p>
            <p className="mt-1">
              <a
                style={{ color: stroke != '#ffffff' ? stroke : '#000000' }}
                className="font-bold underline "
                href="https://twitter.com/jakeacasey"
              >
                If this helped you, follow me on twitter!{' '}
              </a>
            </p>
          </div>
          <div className="flex items-end justify-end mt-5 space-x-2 mr-11 md:mr-9 lg:mr-16">
            <StrokeSelector
              color={stroke}
              handleChange={(color) => updateStroke(color.hex)}
            />
            <StrokeSelector
              color={backgroundColor}
              handleChange={(color) => {
                updateBackgroundColor(color.hex);
                updateFill(color.hex);
              }}
            />
            {/* <StrokeSelector
              color={fill}
              handleChange={(color) => updateFill(color.hex)}
            /> */}
          </div>
          <div className="flex flex-wrap mb-8">
            <Icon
              iconName="activity"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="airplay"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="alertcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="alertoctagon"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="alerttriangle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="aligncenter"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="alignjustify"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="alignleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="alignright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="anchor"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="aperture"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="archive"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowdowncircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowdownleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowdownright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowdown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowleftcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowrightcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowupcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowupleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowupright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="arrowup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="atsign"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="award"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="barcharttwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="barchart"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="batterycharging"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="battery"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="belloff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="bell"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="bluetooth"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="bold"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="bookopen"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="book"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="bookmark"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="box"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="briefcase"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="calendar"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cameraoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="camera"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cast"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="checkcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="checksquare"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="check"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevrondown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronsdown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronsleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronsright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chevronsup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="chrome"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="circle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="clipboard"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="clock"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="clouddrizzle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cloudlightning"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cloudoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cloudrain"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cloudsnow"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cloud"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="code"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="codepen"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="codesandbox"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="coffee"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="columns"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="command"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="compass"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="copy"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerdownleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerdownright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerleftdown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerleftup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerrightdown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerrightup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerupleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cornerupright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="cpu"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="creditcard"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="crop"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="crosshair"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="database"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="delete"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="disc"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="dividecircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="dividesquare"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="divide"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="dollarsign"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="downloadcloud"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="download"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="dribbble"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="droplet"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="edittwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="editthree"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="edit"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="externallink"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="eyeoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="eye"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="facebook"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="fastforward"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="feather"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="figma"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="fileminus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="fileplus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="filetext"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="file"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="film"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="filter"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="flag"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="folderminus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="folderplus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="folder"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="framer"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="frown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="gift"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="gitbranch"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="gitcommit"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="gitmerge"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="gitpullrequest"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="github"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="gitlab"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="globe"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="grid"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="harddrive"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="hash"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="headphones"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="heart"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="helpcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="hexagon"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="home"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="image"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="inbox"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="info"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="instagram"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="italic"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="key"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="layers"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="layout"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="lifebuoy"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="linktwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="link"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="linkedin"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="list"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="loader"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="lock"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="login"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="logout"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="mail"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="mappin"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="map"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="maximizetwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="maximize"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="meh"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="menu"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="messagecircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="messagesquare"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="micoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="mic"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="minimizetwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="minimize"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="minuscircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="minussquare"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="minus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="monitor"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="moon"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="morehorizontal"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="morevertical"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="mousepointer"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="move"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="music"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="navigationtwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="navigation"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="octagon"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="package"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="paperclip"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="pausecircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="pause"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="pentool"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="percent"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phonecall"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phoneforwarded"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phoneincoming"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phonemissed"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phoneoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phoneoutgoing"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="phone"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="piechart"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="playcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="play"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="pluscircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="plussquare"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="plus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="pocket"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="power"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="printer"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="radio"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="refreshccw"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="refreshcw"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="repeat"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="rewind"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="rotateccw"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="rotatecw"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="rss"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="save"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="scissors"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="search"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="send"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="server"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="settings"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="sharetwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="share"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="shieldoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="shield"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="shoppingbag"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="shoppingcart"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="shuffle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="sidebar"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="skipback"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="skipforward"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="slack"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="slash"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="sliders"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="smartphone"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="smile"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="speaker"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="square"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="star"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="stopcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="sun"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="sunrise"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="sunset"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="tablet"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="tag"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="target"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="terminal"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="thermometer"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="thumbsdown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="thumbsup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="toggleleft"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="toggleright"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="tool"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="trashtwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="trash"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="trello"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="trendingdown"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="trendingup"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="triangle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="truck"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="tv"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="twitch"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="twitter"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="type"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="umbrella"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="underline"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="unlock"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="uploadcloud"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="upload"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="usercheck"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="userminus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="userplus"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="userx"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="user"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="users"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="videooff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="video"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="voicemail"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="volumeone"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="volumetwo"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="volumex"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="volume"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="watch"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="wifioff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="wifi"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="wind"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="xcircle"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="xoctagon"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="xsquare"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="x"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="youtube"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="zapoff"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="zap"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="zoomin"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
            <Icon
              iconName="zoomout"
              downloadIcon={downloadIcon}
              stroke={stroke}
              fill={fill}
              backgroundColor={backgroundColor}
            />
          </div>
          <div className="mb-10 ml-4 text-gray-500">
            <span className="font-bold">*</span> The illusion you see between
            icons is called the Hermann grid illusion. It was found by Ludimar
            Hermann in 1870.
          </div>
        </Page>
      </div>
    </div>
  );
};

let Icon = ({ downloadIcon, iconName, stroke, fill, backgroundColor }) => {
  return (
    <>
      <div className="mt-4 ml-4">
        <div
          onClick={() =>
            downloadIcon({ stroke, fill, backgroundColor, icon: iconName })
          }
          style={{ backgroundColor }}
          className="flex items-center justify-center bg-black cursor-pointer rounded-apple h-15 w-15 "
        >
          <IconSelector icon={iconName} stroke={stroke} fill={fill} />
        </div>
      </div>
    </>
  );
};

let RenderBigIcon = React.forwardRef((props, ref) => {
  let { activeIcon } = props;
  console.log(activeIcon);
  return (
    <div
      ref={ref}
      style={{
        backgroundColor: activeIcon.backgroundColor,
        width: 512,
        height: 512,
      }}
      className="flex items-center justify-center "
    >
      <IconSelector
        size={225}
        icon={activeIcon.icon}
        stroke={activeIcon.stroke}
        fill={activeIcon.fill}
      />
    </div>
  );
});

export default Home;
